export const TEMPLATE_TEAMS = [
	'Argentinos Jrs',
	'Arsenal',
	'Atlético Tucumán',
	'Banfield',
	'Barracas Central',
	'Central Córdoba',
	'Colón',
	'Defensa y Justicia',
	'Estudiantes',
	'Gimnasia',
	'Huracán',
	'Independiente',
	'Lanús',
	"Newell's",
	'Patronato',
	'Platense',
	'Racing',
	'Riber Plate',
	'Rosario Central',
	'San Lorenzo',
	'Sarmiento',
	'Talleres',
	'Tigre',
	'Unión',
	'Vélez',
	'Godoy Cruz',
	'Boca Juniors',
	'Aldosivi'
];
